# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'ManageEXP/ManageEXP.Solution/ManageEXP.Solution.sln'
  library: 'ManageEXP/ManageEXP.Solution/ManageEXP.Domain/ManageEXP.Domain.csproj'
  webApi: 'ManageEXP/ManageEXP.Solution/ManageEXP.WebApi/ManageEXP.WebApi.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

