FROM postgres

ENV POSTGRES_PASSWORD root
ENV POSTGRES_USER root
ENV POSTGRES_DB manageExp_core


# docker build . -t intranet-database
# docker run  -p 5432:5432 --name intranet-database intranet-database