FROM postgres

ENV POSTGRES_PASSWORD root
ENV POSTGRES_USER root
ENV POSTGRES_DB manageExp_database

# docker build . -t manage-exp-database
# docker run  -p 5432:5432 --name manage-exp-database manage-exp-database